
site_name: Gestoría de Autoconsumo
docs_dir: 'docs'
copyright: Copyright &copy; 2023 GA   
dev_addr: 0.0.0.0:8000
theme:
  logo:  https://github.com/asolear/assets/blob/master/logoGA.png?raw=true
  favicon: https://github.com/asolear/assets/blob/master/logoGA.png?raw=true
  name: material
  palette:
    - scheme: slate
      primary: blue grey
      accent: orange
  features:
    - navigation.tabs
  language: es
extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:info@gestoriadeautoconsumo.com?subject=Contacto blog QR&body=Quiero comentarte un tema tecnico ...
    - icon: fontawesome/solid/phone
      link: tel:+34 600366211
  generator: false
  analytics:
    provider: google
    property: G-XXXXXXXXX
  consent:
    title:  Consentimiento de Cookies
    description: >- 
      Utilizamos cookies para reconocer sus visitas repetidas y preferencias, así como
       como para medir la eficacia de nuestra documentación y si los usuarios
       encuentran lo que están buscando. Con su consentimiento, nos está ayudando a
       mejorar nuestra documentación.
    cookies:
      analytics:
        name: Google Analytics
        checked: true
    actions:
      - accept
      - reject      
  alternate:
    - name: Espanol
      link: /
      lang: es
    - name: English
      link: /
      lang: en
    - name: Italiano
      link: /
      lang: it
plugins:
  - search





